name: Build with vendor

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, bcmath, zip

    - name: Install dependencies
      run: composer install --no-dev --ignore-platform-reqs

    - name: Zip project (incluindo vendor)
      run: |
        zip -r viper-with-vendor.zip \
          artisan app bootstrap config database public resources routes storage vendor composer.json composer.lock

    - name: Upload artifact ZIP
      uses: actions/upload-artifact@v3
      with:
        name: viper-with-vendor
        path: viper-with-vendor.zip
